# Aprendizaje Automatico Intro Julia

##### ¿Sería necesario realizar este preprocesado cuando las entradas son los valores de intensidad de cada pixel en una imagen en blanco y negro? ¿Por qué?

###### Para el caso de las imágenes en blanco y negro, el preprocesado de normalización no sería necesario. Esto se debe a que las imágenes en blanco y negro tienen un rango de valores que varía de 0 (negro) a 255 (blanco). Este rango ya está normalizado, ya que representa la intensidad de la luz en la imagen

#####  En este tipo de normalización, si min=max, se puede realizar otro preprocesadodistinto en este atributo, ¿en qué consistiría?

###### Si el valor mínimo y el máximo de un atributo son iguales, significa que todos los valores de ese atributo son iguales. En este caso, ese atributo no aporta información útil al modelo porque no hay variabilidad en sus valores. Por lo tanto, un posible preprocesado para este atributo sería eliminarlo del conjunto de datos, ya que no contribuye a la predicción

##### Sabiendo que los modelos de Aprendizaje Automático en general suponen que los patronesse distribuyen en filas, pero en el mundo de las RR.NN.AA. se distribuyen en columnas, ¿en qué casos habría que normalizar cada fila por separado y en qué casos habría que normalizar cada columna por separado?

###### Depende un poco del problema a tratar -> Ejemplo Lista de alumnos en filas y cada columna es una materia 
###### Si estás viendo el desempeño de cada estudiante en diferentes materias, normalizar por fila te ayuda a comparar cómo les va en cada materia sin que las calificaciones altas o bajas de otros estudiantes afecten demasiado.
###### Si estás observando diferentes materias y quieres asegurarte de que las calificaciones en cada materia estén en la misma escala, normalizar por columna es útil para que ninguna materia tenga un impacto desproporcionado en los modelos o análisis.  

#####  ¿Por qué no se realiza en problemas de clasificación?

###### La normalización de los datos de salida no se realiza en problemas de clasificación porque en la clasificación, el objetivo es predecir una etiqueta de clase, no una cantidad continua. En otras palabras, en un problema de clasificación, las salidas son categorías discretas, no números continuos. Por lo tanto, no hay una "mejor" salida que la otra; simplemente hay diferentes categorías.

##### Primera semana

In [1]:
using DelimitedFiles 
dataset = readdlm("../iris/iris.data",','); ## Cargar el dataset
##### Crear una matriz con las entradas y otra con las salidas deseadas, cada una con el tipo más adecuado.
##### ¿Qué dimensiones tienen las matrices? ->  (150, 4) y (150, 1) respectivamente.

150×5 Matrix{Any}:
 5.1  3.5  1.4  0.2  "Iris-setosa"
 4.9  3.0  1.4  0.2  "Iris-setosa"
 4.7  3.2  1.3  0.2  "Iris-setosa"
 4.6  3.1  1.5  0.2  "Iris-setosa"
 5.0  3.6  1.4  0.2  "Iris-setosa"
 5.4  3.9  1.7  0.4  "Iris-setosa"
 4.6  3.4  1.4  0.3  "Iris-setosa"
 5.0  3.4  1.5  0.2  "Iris-setosa"
 4.4  2.9  1.4  0.2  "Iris-setosa"
 4.9  3.1  1.5  0.1  "Iris-setosa"
 ⋮                   
 6.9  3.1  5.1  2.3  "Iris-virginica"
 5.8  2.7  5.1  1.9  "Iris-virginica"
 6.8  3.2  5.9  2.3  "Iris-virginica"
 6.7  3.3  5.7  2.5  "Iris-virginica"
 6.7  3.0  5.2  2.3  "Iris-virginica"
 6.3  2.5  5.0  1.9  "Iris-virginica"
 6.5  3.0  5.2  2.0  "Iris-virginica"
 6.2  3.4  5.4  2.3  "Iris-virginica"
 5.9  3.0  5.1  1.8  "Iris-virginica"

#### 1 ) ¿Cuál será el resultado de las siguientes llamadas?

In [ ]:

inputs = dataset[:,1:4]; ## Salida esperada: 150×4 Array{Float64,2}
targets = dataset[:,5];  ## Salida esperada: 150-element Array{Any,1}

 ##### Para ver de qué tipo es una variable, se puede usar la función typeof

In [ ]:
typeof(Array{Float64,2}) ## Salida esperada: DataType
typeof(DataType) ## Salida esperada: DataType
typeof(Any)  ## Salida esperada: DataType

##### Comprobar si una variables de un tipo determinado, se puede usar la función isa.

In [ ]:

isa(DataType, Any)  ## Salida esperada: True
isa(Any, Any) ## Salida esperada: True
isa(Array{Float32,2}, Any) ## Salida esperada: True
isa(typeof(Array{Float64,2}), Any)  ## Salida esperada: True

##### Usar la función convert, que intenta hacer una conversión a un tipo especificado, es necesario convertir los datos que usaremos, de Array{Any,2} a Array{Float32,2}

In [ ]:
#inputs = convert(Array{Float32,2},inputs); 
#targets = convert(Array{Float32,1},targets); 

#####  Si es un problema de clasificación en dos clases y elarchivo tiene valores numéricos de 0 y 1 para cada clase, esto se podría convertir en valores booleanos con algo como:

In [ ]:
#targets = convert(Array{Bool,1}, targets);

##### La función que calcula el cuadrado de un número de la siguiente manera:

In [ ]:
cuadrado(x::Real) = x*x 
cuadrado.([1 2 3]) 
[cuadrado(x) for x in [1 2 3]] 


##### Operación Suma

In [ ]:
suma(a::Real, b::Real) = a+b 
suma.([1 2 3],[2 3 4])

###### ¿Cuál será el resultado de hacer suma.(1,[2 3 4]) y suma.([1 2 3],3)?

In [ ]:
suma.(1,[2 3 4])

In [ ]:
suma.([1 2 3],3)

##### Es equivalente escribir estas líneas:

In [ ]:
inputs = Float32.(inputs); 
inputs = [Float32(x) for x in inputs]; 
inputs = convert(Array{Float32,2},inputs); 

####  ¿Cuál será el resultado de las siguientes llamadas?

In [ ]:
typeof(inputs) 

isa(inputs, Any) 
isa(inputs, Array) 
isa(inputs, Array{Float32,2}) 
isa(inputs, Array{Real,2}) 
isa(inputs, Array{Number,2}) 
isa(inputs, Array{Any,2}) 
isa(inputs, Array{<:Real,2}) 
isa(inputs, Array{<:Number,2})
isa(inputs, Array{<:Any,2})

#####  ¿Cuál será el resultado de las siguientes llamadas?

In [ ]:
Array{Float32,2} <: Any
Array{Float32,2} <: Array
Array{Float32,2} <: Array{Any,2}
Array{Float32,2} <: Array{<:Real,2}
Array{Float32,2} <: Array{<:Any,2}

#### Si el problema es de clasificación con 2 clases, y nos dan estas salidas deseadas como valores numéricos 0 o 1, serían equivalentes las siguientes líneas:

In [ ]:
#targets = Bool.(targets); 
#targets = [Bool(x) for x in targets]; 
#targets = convert(Array{Bool,1},targets);

##### De cara a la definición de funciones, es importante tener en cuenta que ambos son subtipos de AbstractArray{Bool,N}

In [ ]:
BitArray{2} <: AbstractArray{Bool,2} 
Array{Bool,2} <: AbstractArray{Bool,2}

##### ¿Qué tipo tendrán los objetos [[]], [[8]] y [[8.]]?

In [ ]:
[[]] ## Salida  []
[[8]] ## Salida [8]
[[8.]] ## Salida [8.0]

##### Para saber el número de filas y/o columnas de una matriz se puede usar la función size

In [ ]:
size(inputs) ## Salida esperada (150, 4)
size(inputs,1) ## Salida esperada 150

##### suele ser interesante introducir comprobaciones para verificar que todo está correcto

In [ ]:
@assert (size(inputs,1)==size(targets,1)) "Las matrices de entradas y 
salidas deseadas no tienen el mismo número de filas"

##### Para crear un vector se pueden escribir sus elementos entre corchetes

In [ ]:
M = [1, 2, 3]

##### Para crear una matriz basta con escribir sus elementos entre corchetes

In [ ]:
M = [1 2 3; 4 5 6] 

##### Para acceder a un elemento de la matriz se indica el nombre de la matriz seguido de la fila y la columna a la que se desea acceder entre corchetes

In [ ]:
M[2,3]

##### ¿Cuál será el resultado de las siguientes llamadas? Al representar un vector como si fuera una matriz, ¿esta será una matriz fila o una matriz columna? ¿La tercera llamada devuelve un vector o una matriz bidimensional?

In [ ]:
typeof([1,2,3]) ## Salida esperada: Vector{Int64}
typeof([1;2;3]) ## Salida esperada: Vector{Int64}
typeof([1 2 3]) ## Salida esperada: Matrix{Int64}
typeof([1 2 3; 4 5 6]) ## Salida esperada: Matrix{Int64}

##### ejemplos, que permiten tomar de la matriz M todas las filas y la primera columna, la primera fila y las columnas a partir de la segunda y la segunda fila y todas las columnas respectivamente

In [ ]:
M[:, 1] ## Salida esperada: [1, 4]
M[1, 2:end] ## Salida esperada: [2, 3]
M[2, :] ## Salida esperada: [4, 5, 6]

##### ¿Qué dimensiones y tamaños tendrán las matrices resultado de estas tres operaciones? ¿Qué dimensión se “pierde” en cada una?

In [ ]:
M[1, end:-1:1] 
M[1, [3, 2, 1]]
## Que dimensiones tienen ? -> (3,) y (3,1) respectivamente
## Tamaños tienen las mastrices resultado ? -> 3 y 3 respectivamente
## Que dimension se pierde en cada una ? -> La segunda y la primera respectivamente

##### Si M es una matriz de 4 dimensiones, cuántas dimensiones tendrán los resultados de las siguientes operaciones?

In [ ]:
M[:, :, :, :] ## Dimensiones ? -> (2, 3, 1, 1)
#M[1, 2, 3, 4] ## Dimensiones ? -> 1D array con los valores de la matriz M en el indice especificado.
#M[1, 2, 3, :] ## Dimensiones ? -> 1D array con los valores de la matriz M en el indice especificado.
#M[:, [1, 2, 3], 4, :] ## Dimensiones ? -> 2D array con los valores de la matriz M en el indice especificado.
M[:, [1, 2, 3], :, :] ## Dimensiones ? -> 3D array con los valores de la matriz M en el indice especificado.
#M[[3, 2], 2, 4, :] ## Dimensiones ? -> 2D array con los valores de la matriz M en el indice especificado.
#M[[3, 2], [2], [4], [1]]  ## Dimensiones ? -> 1D array con los valores de la matriz M en el indice especificado.
#M[1, [1, 2, 3], 4, :] ## Dimensiones ? -> 2D array con los valores de la matriz M en el indice especificado.



In [ ]:
N = [10 20 30; 40 50 60];

##### ¿Por qué da error al intentar ejecutar N*M pero no N.*M? ¿Por qué da error al intentar ejecutar N>30 pero no N.>30?

In [ ]:
#N > 30
N .> 30
## pORQUE DA ERROR ? -> Porque el operador > no esta definido para matrices, solo para escalares.

In [ ]:
M = Array{Float32,2}(undef, 10, 6) 

##### ¿Por qué dará error escribir M = Array{Float32,2}(undef, 10)?

In [ ]:
#M = Array{Float32,2}(undef, 10)
## Porque da error ? -> Porque el constructor Array{Float32,2} espera dos argumentos, el tipo de los elementos y las dimensiones de la matriz.
## y cuantos le pasamos ? -> 3 

#####  ¿Cuál será el resultado de las siguientes llamadas?

In [ ]:
typeof(Array{Float32,2}(undef, 4, 15)) ### Salida esperada: Matrix{Float32}
typeof(Array{Float32,2}) ## Salida esperada: DataType
isa(Array{Float32,2}, Array{Float32,2}) ## Salida esperada: false
isa(Array{Float32,2}(undef, 4, 10), Array{Float32,2}) ## Salida esperada: true

##### Usar las funciones zeros o ones, que crean matrices del tamaño indicado donde todos los elementos son 0 o 1 respectivamente

In [ ]:
zeros(10, 6) 
ones(13)

##### Para concatenar dos vectores

In [ ]:
[[1, 2, 3]; [4, 5, 6]]

##### Para unir matrices, esto se realiza de forma similar, utilizando los corchetes, y separando las matrices por espacio, en caso de querer unirlas añadiendo nuevas columnas (poniendo una “al lado” de la otra), o separando las matrices por “;” en caso de querer unirlas añadiendo nuevas filas (poniendo una “debajo” de la otra). Por supuesto, en el primer caso tiene que coincidir el número de filas, y en el segundo tiene que coincidir el número de columnas.

In [ ]:
[[1 2 3; 4 5 6] [7 8 9; 10 11 12]] 
[[1 2 3; 4 5 6]; [7 8 9; 10 11 12]]

##### ¿Cuál será el resultado de cada una de las dos operaciones anteriores?

In [ ]:
[[1 2 3; 4 5 6] [7 8 9; 10 11 12]]

In [ ]:
[[1 2 3; 4 5 6]; [7 8 9; 10 11 12]]

#####  Si [[1, 2, 3]; [4, 5, 6]] permite concatenar vectores, ¿cuál será el resultado de las siguientes operaciones? ¿Cuál será el tipo del resultado?

In [ ]:
[[1, 2, 3] [4, 5, 6]] 

In [ ]:
[[1, 2, 3], [4, 5, 6]] 

In [ ]:
[[1 2 3] [4 5 6]] 

In [ ]:
[[1 2 3]; [4 5 6]] 

In [ ]:
[[1 2 3], [4 5 6]]